#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Mise à jour de la base des applications de bureau
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications || true
    fi

    # Rafraîchissement du cache d'icônes hicolor
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
    fi
fi

exit 0
